stages: [check, test]

variables:
  GIT_STRATEGY: clone  
  GIT_DEPTH: 0   
  BASH_ENV: /dev/null        

.root-template:
  tags: [wsl-shell]
  before_script:
    - eval $(opam env)
    - cd 1Lab

format:
  stage: check
  extends: .root-template
  script:
    - dune build @fmt  

lint:
  stage: check
  extends: .root-template
  script:
    - dune build --profile=release @check 

build:
  stage: check
  extends: .root-template
  script:
    - dune build --profile=release
test:
  stage: test
  extends: .root-template
  script:
    - dune runtest --no-buffer --profile=release