stages: [check, test]

variables:
  GIT_STRATEGY: clone  
  GIT_DEPTH: 0   
  BASH_ENV: /dev/null        

.root-template:
  tags: [wsl-shell]
  before_script:
    - eval $(opam env)

format:
  stage: check
  extends: .root-template
  script:
    - FILES="$(git ls-files '*.ml' '*.mli' 'src/**/*.ml' 'src/**/*.mli' 'lib/**/*.ml' 'lib/**/*.mli' 'test/**/*.ml' 'test/**/*.mli' || true)"
    - |
      if [ -n "$FILES" ]; then
        ocamlformat --check $FILES
      else
        echo "No OCaml files"
      fi

lint:
  stage: check
  extends: .root-template
  script:
    - dune build @all --profile=release

test:
  stage: test
  extends: .root-template
  script:
    - dune runtest --no-buffer --profile=release